
<?php
$contacts = $this->getContacts();
?>
<div id="contactslist">
    <h2 style="margin-left:35%;">Data View</h2>
   <div style="margin-bottom:20px"> <a href="<?php echo $block->getUrl('contacts/index/insert');?>" class="action primary">Insert</a></div>
    <table>
        <tr>
            <th>Name</th>
            <th>email</th>
            <th>comment</th>
            <th>Action</th>
        </tr>
        <?php foreach ($contacts as $contact): ?>
            <tr>
                <td><?php echo $contact->getName(); ?></td>
                <td><?php echo $contact->getEmail(); ?></td>
                <td><?php echo $contact->getComment(); ?></td>
               
              <td>  <a href="<?php echo $block->getUrl('contacts/index/edit').'id/'.$contact->getId('pfay_contacts_id'); ?>" class="action primary">Edit</a>
                <a href="<?php echo $block->getUrl('contacts/index/delete').'id/'.$contact->getId('pfay_contacts_id'); ?>" class="action primary">Delete</a></td>

            </tr>
        <?php endforeach; ?>
     
    </table>
</div>  